### ISSUE TITLE
Outfit textures when worn are missing

### ISSUE THREAD

**Issue by Pengu-Hunter** [Blaez-Dev/RWBYM-2.0#14]
I haven't found the change logs so I don't know if you have made a comment or not about how complete the implementation of the outfits is, but when I find a 'Dust Till Dawn' shop that has Qrow's weapon, outfit, some ammo and some dust, in a chest and put the Qrow outfit on and look at the character model it has the minecraft black and purple checker pattern to show that the texture is missing.

**Comment by Blaez-Dev** [comment]
This is a mod conflict, there is nothing we can do to help you.

**Comment by Pengu-Hunter** [comment]
Thanks for replying so quickly the conflict was with 'Hammer Core'.

**Comment by Blaez-Dev** [comment]
No worries, glad to have helped.
