### ISSUE TITLE
Yang Semblance bug

### ISSUE THREAD

**Issue by CmdrJane** [Blaez-Dev/RWBYM-2.0#17]
So i discovered that Yang semblance is cost around 37 aura point. Its provides strength buff. But if u dont have enough aura points and you use your ability once its reach zero the aura regeneration will stuck. Well it just will constanly drain your energy until consume full price of ability which will break regenration contuniously. Video included. And sorry for my bad english.

https://youtu.be/VxEPRA8El9c

**Comment by CmdrJane** [comment]
forgot to say that this is 4.1.3 mod version on minecraft forge 14.23.5.2847, no other mod being instaled on client.

**Comment by Blaez-Dev** [comment]
I looked into it and will have a fix out in the next build.

**Comment by CmdrJane** [comment]
Well thats fast

**Comment by Blaez-Dev** [comment]
I'm just pretty good at responding too bugs that pop up if its something quick I try to do it so theres very little on the backlog.
