### ISSUE TITLE
Deathloop when used together with Potioncore mod

### ISSUE THREAD

**Issue by Keltas** [Blaez-Dev/RWBYM-2.0#22]
After installing rwbym-4.3.4.jar together with PotionCore-1.8_for_1.12.2.jar the game essentially becomes permadeath. Once you die of any cause, when clicking respawn you die immediately again as you respawn with 0 health. I speculate that it may be some weird interaction between the revival effect from potioncore and aura acting as health in RWBYM.

**Comment by Blaez-Dev** [comment]
Can't fix every bug, particularly this one as its not on our end. Sorry you might have better luck with contacting potioncore's developer and have them investigate it as its likely a simple over-sight that can be fixed in afew minutes.

**Comment by Keltas** [comment]
No problem. I've reported it on PotionCore earlier just thought I would report it here as well in case I was wrong and it was on this end.
