### ISSUE TITLE
Armour Geist crashing internal server on launch

### ISSUE THREAD

**Issue by GreenMageYouTube** [Blaez-Dev/RWBYM-2.0#23]
I've been playing a internal server (offline single player) for about sixty hours and I decided to finally try fighting a Armour Geist as I had the spare armour to make four. Long story short, the game crashed as soon as it attacked me and now freezes on launch every time I try to play again. I have already tried to remove it before launching via a mob blacklister with no success. Has anybody else had this issue? I'm running about sixty other mods so if it is a mod conflict I don't know how to figure out what is causing it.
[crash-2019-12-31_17.10.40-server.txt](https://github.com/Blaez-Dev/RWBYM/files/4013697/crash-2019-12-31_17.10.40-server.txt)

**Comment by Blaez-Dev** [comment]
I'm drunk man its new years. I'll chase it down real quick and make a note if its not a simple fix.

**Comment by GreenMageYouTube** [comment]
Thank you so much Blaez-Dev, sorry about interrupting your new years. I am willing to wait if you wish to continue festivities.
Best of luck and please have a good evening
-Green

**Comment by Blaez-Dev** [comment]
https://cdn.discordapp.com/attachments/629612044471107584/662286506945282058/rwbym-4.3.7.jar try this version. if it isn't fixed then send me another crash log and ill see if I can narrow it down however I've not had it happen in personal testing so it might boil down to a mod incompatibility for some reason. I've done a pretty drastic measure to see if that fixes the issue however there's no promises it works.

**Comment by GreenMageYouTube** [comment]
Thank you, the internal server is now working fine. I really appreciate the
help and I love the mod
