### ISSUE TITLE
Aura breaks /kill

### ISSUE THREAD

**Issue by Oonicorn** [Blaez-Dev/RWBYM-2.0#26]
As long as "Aura blocks damage" is enabled, running /kill will suspend the player in a state of both being alive and being dead. The player animation will be stuck tinted red, the world will turn diagonal and shake constantly from first-person perspective, mobs will no longer attack the player, the respawn screen will not appear, and no further damage or /kill commands will make it appear either.

**Comment by Blaez-Dev** [comment]
this is a issue with some other mod you have on board I used /kill and plenty of other methods of dying when in testing you are the only person to report this issue out of plenty of other users. what mod is causing this I can not tell you however it is a mod conflict on your end.
