### ISSUE TITLE
World Gen Question

### ISSUE THREAD

**Issue by Pengu-Hunter** [Blaez-Dev/RWBYM-2.0#27]
This is minecraft 1.12.2 RWBYM 4.4.7, the following is a screen short of FTB Utils map showing a lot of Qrow bars and one dust till dawn clustered together, I was wondering if this is intended behavior
 or if I need to delete and let the game recreate my RWBYM config to change this.

Regards Pengu

![Capture](https://user-images.githubusercontent.com/49605318/80298998-7ab94480-87d4-11ea-93ca-8da7345e18d1.PNG)

**Comment by Blaez-Dev** [comment]
Those shops are not intended to spawn like that however, those structures no longer spawn regardless in the current development version as the shops have been changed to spawn in a sort of market like structure in every village. so its not something you'll need to worry about for much longer.
