### ISSUE TITLE
[1.12.2] Crash upon entering world

### ISSUE THREAD

**Issue by Secretname2009** [Blaez-Dev/RWBYM-2.0#28]
I was trying to make a custom modpack but i found out that this mod is crashing upon trying to enter a world. It doesnt matter if the world was previously created or newly created.
[crash-2020-06-27_14.24.03-server.txt](https://github.com/Blaez-Dev/RWBYM/files/4840549/crash-2020-06-27_14.24.03-server.txt)

**Comment by Blaez-Dev** [comment]
I'd suggest downgrading to a previous version of forge, those newer versions have alot of issues. even trying to setup a development environment for it is pretty messy from what I've noticed. try that again on 2847 or older. as they changed things to be more in line with the newer versions and with mods not updated with the changes alot of things aren't working properly.

**Comment by Secretname2009** [comment]
Im sorry for not responding earlier but i think there was a mod misbehaving as i now have recreated the modpack and it works normal on Forge version 14.23.5.2854 
I do not know which mod was causing this crash and i wish i knew.
