### ISSUE TITLE
[1.12.2] Baubles not rendering when installed alongside RWBYM (Tested w/ Botania/Artifacts)

### ISSUE THREAD

**Issue by ErikaRedmark** [Blaez-Dev/RWBYM-2.0#31]
Versions: 
Minecraft 1.12.2
Baubles 1.12-1.5.2
Botania r1.10-363
RWBYM 4.6.4 Indev 5
Forge 14.23.5.2847

I have a modpack that has a lot more mods, but after trimming out everything else, I can still replicate the issue with just the ones above. I am using Botania with Baubles as that makes the problem the most obvious.

1) make a new world with the four mods above
2) wear any cosmetic bauble (most obvious would be Flügel Tiara, for instance the Phoenix Wings version)
3) Observe how it does not render.

Attempt the same steps without RWBYM installed, and the wings render fine.

This isn't just Botania. Anything that uses Baubles has issues -- for instance, I also tried without Botania but with Artifacts, and tried wearing the Obsidian Skull. It normally renders on the player's belt region, but with RWBYM installed it does not.

**Comment by Blaez-Dev** [comment]
this is because rwby uses a custom player renderer for  faunus parts ect. this incompatibility is known and  not fixable without loss of said functionality.
