### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by Hakaisuru** [Blaez-Dev/RWBYM-2.0#32]
Anytime I launch the game with minecraft forge 1.12.2 I get this: 

 net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RWBYM (rwbym)
Exit Code: -1

**Comment by Blaez-Dev** [comment]
Pass me a crash log and I'll review it. however we don't support forge 2847+ so check your version and keep that in mind.

**Comment by Hakaisuru** [comment]
So I actually had the wrong forge 1.12.2   -_-'   but after downloading and switching it in the launcher it works flawlessly. Thank you!

**Comment by Blaez-Dev** [comment]
np

**Comment by gears1021** [comment]
I'm so confused, when i try to roll back to an older forge version before 2847 it keeps crashing with the same message
